# Plugin Information #
name: SlimeFood
version: 0.2
author: GamingOnInsulin
description: 一个普通的Slimefun插件，旨在添加新的食物种类。
website: https://github.com/SlimefunGuguProject/SlimeFoodPlugin

# Plugin Options #
options:
  auto-update: true
